Fix error when trying to modify a task that doesn't have an environment.
Fixes: TaskEnvironmentPanel.py", line 96, in loadControls
    environmentName = environmentNames[0]
IndexError: list index out of range